### ISSUE TITLE
Code & Pretrained Models

### ISSUE THREAD

**Issue by mmaaz60** [mbzuai-oryx/Video-ChatGPT#1]
Please note that this is an ongoing work where we are working on improving our architecture design and finetuning on the video instruction data. We will release our codes and pretrained models very soon (Before Jun 17, 2023). Stay tuned!

**Comment by AnaRhisT94** [comment]
Thanks!

**Comment by mmaaz60** [comment]
The codes, pretrained models and dataset are released! Happy to help in case if you face any issues. Thanks
