### ISSUE TITLE
Why is important to change the order of content['q'] and <video>?

### ISSUE THREAD

**Issue by shufangxun** [mbzuai-oryx/Video-ChatGPT#10]
As the comment says: https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/scripts/convert_instruction_json_to_training_format.py#L28

**Comment by mmaaz60** [comment]
Hi @shufangxun,

Thank You for your interest in our work. The comment is referring to the importance of adding `<video>` token to the annotation which is going to be replaced with the actual video content during training. It is not referring to the order of `content['q']` and `<video>`. However, during training this alternate order could be considered as form of regularization.

Please let me know if it clarifies the confusion. Thank you

**Comment by shufangxun** [comment]
Thanks for your reply! by the way, how much is the performance difference between these two ways？
