### ISSUE TITLE
Same output for any system prompt

### ISSUE THREAD

**Issue by yangzhj53** [mbzuai-oryx/Video-ChatGPT#103]
I followed the steps in the tutorial to evaluate the results of the model on MSVD-QA, but I found that regardless of how my system prompt was set, even if the model was asked to answer 'Yes', its answer was almost consistent. Is this reasonable?

![微信图片_20240505204617](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/94351765/1b442c17-a186-494c-8725-bf83a4d338ae)

**Comment by mmaaz60** [comment]
Hi @yangzhj53,

Thank you for your interest in our work. It looks like the model is not respecting the system/user prompt in this particular case which can be considered as one of the limitations of the model.

May be, using some language only instruction data (e.g. ShareGPT data) along with the VideoInstruct-100K improves the performance.

Please do share if you fix this trend. Thank you and good luck :)
