### ISSUE TITLE
Why does "No module named 'video chatgpt'" appear? What should I do next?

### ISSUE THREAD

**Issue by woc66666** [mbzuai-oryx/Video-ChatGPT#109]
I followed the steps in the README file to create an environment with conda and install FlashAttention for training. Then, I followed the steps in docs/offline demo.md to "Download Video-ChatGPT weights" and "Prepare LLaVA weights". And download the sample video, and finally run the demo script there is a problem, you can help to see why?

![Uploading PixPin_2024-06-04_19-29-32.jpg…]()

**Comment by biphobe** [comment]
@woc66666 Try `python -m video_chatgpt.demo.video_demo` instead of `python video_chatgpt/demo/video_demo.py` as seen [here](https://github.com/mbzuai-oryx/Video-ChatGPT/pull/101/files).

**Comment by mmaaz60** [comment]
Hi @woc66666,

I appreciate your interest in our work. If the solution suggested by @biphobe is not working, try adding the current directory into your Python path as `export PYTHONPATH="./:$PYTHONPATH"`. I hope it will solve the issue. Thank You.
