### ISSUE TITLE
How to download the vidoes?

### ISSUE THREAD

**Issue by lucasjinreal** [mbzuai-oryx/Video-ChatGPT#110]
How to download the vidoes?

**Comment by mmaaz60** [comment]
Hi @lucasjinreal,

I appreciate your interest in our work and apologize for the late reply as I was traveling. Please use the links provided at https://github.com/mbzuai-oryx/Video-ChatGPT/issues/98#issuecomment-2066219023 to download the videos.

Please let me know if you face any issues. Thank You.
