### ISSUE TITLE
GoogleDrive of Clip-Features

### ISSUE THREAD

**Issue by SeuXiao** [mbzuai-oryx/Video-ChatGPT#112]
Could you please provide the Google Drive link of ActivityNet_Train_Video-ChatGPT_Clip-L14_Features.zip? Sharepoint does not allow downloading using wget.

**Comment by mmaaz60** [comment]
Hi @SeuXiao,

I appreciate your interest in our work. You can find the google drive links to download the videos [here](https://github.com/mbzuai-oryx/Video-ChatGPT/issues/98#issuecomment-2066219023).

Thanks

**Comment by SeuXiao** [comment]
Thanks for you reply.
What I want to know is that why not fine tune the LLM.

**Comment by mmaaz60** [comment]
Hi @SeuXiao,

Thank you for your interest in our work. At the development time, we do not have enough resources to fine-tune complete LLM. However, it would be interesting to see how the model performs when finetuning the LLM as well.

Please do share if you get some results. Good Luck!
