### ISSUE TITLE
Question about the test json of msvd and msrvtt dataset

### ISSUE THREAD

**Issue by butemp** [mbzuai-oryx/Video-ChatGPT#113]
I have a small question, in this [link](https://mbzuaiac-my.sharepoint.com/personal/hanoona_bangalath_mbzuai_ac_ae/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FQuantitative%5FEvaluation%2FZero%5FShot%5FQA) you provide the relevant test set, but msvd and msrvtt are both val_Qa.json, is the experimental result of this work on test_qa or val_qa

**Comment by mmaaz60** [comment]
Hi @butemp 

Thank you for your interest in our work. We use val sets for MSVD and MSRVTT. Thanks.
