### ISSUE TITLE
How to data video download with wget

### ISSUE THREAD

**Issue by ooooohira** [mbzuai-oryx/Video-ChatGPT#126]
Hello ! , Thanks for great work.

I wanna download training video data from [onedrive](https://mbzuaiac-my.sharepoint.com/personal/hanoona_bangalath_mbzuai_ac_ae/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FData&ga=1).

How to download the data Activitynet_Train_Videos_Video_ChatGPT.zip using wget command?
I can't find download url?

**Comment by zijian0312** [comment]
could you teach me how to use wgert to download it
