### ISSUE TITLE
OSError: It looks like the config file at 'video_chatgpt-7B.bin' is not a valid JSON file.

### ISSUE THREAD

**Issue by yavuzc78** [mbzuai-oryx/Video-ChatGPT#13]
python scripts/apply_delta.py --base-model-path video_chatgpt-7B.bin --target-model-path LLaVA-Lightning-7B-v1-1 --delta-path liuhaotian/LLaVA-Lightning-7B-delta-v1-1

why Tis issue?
OSError: It looks like the config file at 'video_chatgpt-7B.bin' is not a valid JSON file.

**Comment by mmaaz60** [comment]
Hi @yavuzc78,

Thank you for your interest in our work. The `--base-model-path` should point out to the LLaMA checkpoints, which can be obtained following the instructions [here](https://huggingface.co/docs/transformers/main/model_doc/llama).

```
python scripts/apply_delta.py \ 
        --base-model-path <path to LLaMA 7B weights> \
        --target-model-path LLaVA-Lightning-7B-v1-1 \
        --delta-path liuhaotian/LLaVA-Lightning-7B-delta-v1-1
```

Alternatively you can download the ready LLaVA-Lightening-7B weights from [mmaaz60/LLaVA-Lightening-7B-v1-1](https://huggingface.co/mmaaz60/LLaVA-7B-Lightening-v1-1).

**Comment by charchit7** [comment]
Hey @mmaaz60 @hanoonaR when downloading the ready LLaVA-Lightening-7B weights from [mmaaz60/LLaVA-Lightening-7B-v1-1](https://huggingface.co/mmaaz60/LLaVA-7B-Lightening-v1-1).

where do we need to put that? path is not mentioned in the readme. If you could please tell me. That would really help.

**Comment by mmaaz60** [comment]
Hi @charchit7

You can store it anywhere and pass it as `--model-name` argument while running the demo.

```
python video_chatgpt/demo/video_demo.py 
        --model-name <path to the LLaVA-Lightening-7B-v1-1 weights prepared in step 3> \
        --projection_path <path to the downloaded video-chatgpt weights>
```

**Comment by charchit7** [comment]
Got it. Thank you @mmaaz60 for a prompt reply :)

**Comment by charchit7** [comment]
Hey @mmaaz60 it works and the whole code base is beautifully written. Thank you!
