### ISSUE TITLE
Finetuning recipe for custom dataset

### ISSUE THREAD

**Issue by nahidalam** [mbzuai-oryx/Video-ChatGPT#2]
Can you please share some finetuning recipe for custom dataset?

**Comment by mmaaz60** [comment]
Hi @nahidalam,

Thank You for your interest in our work. We finetune for 3 epochs using 32 batch size in total. In the deployed version, we only finetuned the linear layer projecting visual features to Vicuna input space.

We are in the process of making pretrained models and the code ready for release. It should be released withing one month. Stay tuned and enjoy the demo!
