### ISSUE TITLE
Alternative choices for linear layer

### ISSUE THREAD

**Issue by Kratos-Wen** [mbzuai-oryx/Video-ChatGPT#20]
Thank you for the very excellent work! In your paper you mentioned that you experimented with more complex network models in addition to linear layers, will you publish the details and evaluation results of the other attempts?

Thanks in advance!

**Comment by mmaaz60** [comment]
Hi @Kratos-Wen,

Thanks for your interest in our project and for bringing up this question.

In our experiments, we found a linear layer architecture met our performance objectives quite effectively. Although the potential of more complex designs was noted, we didn't dive into that depth of experimentation and hence, we lack specific numbers related to these designs.

An important point to consider is that these complex models may not necessarily outperform our chosen architecture. Major reason being their inability to initialize from the pretrained LLaVA weights.

Hope this clarifies things a bit. Thank You.

**Comment by Kratos-Wen** [comment]
Thanks, that pretty much answers my question! Congratulations again on your results!
