### ISSUE TITLE
hardware requirement for deploying video-chatgpt locally

### ISSUE THREAD

**Issue by Xinxinatg** [mbzuai-oryx/Video-ChatGPT#27]
Thanks for your wonderful work! I am wondering whether it would be possible to deploy it on a server with 2 A30 gpus each of which has 24 GB VRAM.

**Comment by mmaaz60** [comment]
Hi @Xinxinatg,

Thank you for your interest in our work. Our model can be easily deployed on a single 24 GB GPU. It means it can be deployed on a single A30 GPU as well. Thank You.

**Comment by Xinxinatg** [comment]
that's great news, thank you!

**Comment by mmaaz60** [comment]
You are most welcome!
