### ISSUE TITLE
Video uploading is not working and I want to design website for you.

### ISSUE THREAD

**Issue by apneduniya** [mbzuai-oryx/Video-ChatGPT#3]
I was trying to text _**Video-ChatGPT**_, but it was showing error after I clicked on the `Upload Video` button.

![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/113763427/f049e72f-07c0-49db-a7d6-26bfd809c58d)

With this, I also want to contribute to this project by making an _appealing website_ for making it a bit more attractive and pleasing to others as well as I would also make a documentation in the website which make users understand how to use it ⚡.

**Comment by mmaaz60** [comment]
Hi @apneduniya,

Thank you for your interest in our work. I just verified and the upload button is working for me. Could you please retry and share the exa

**Comment by apneduniya** [comment]
Yeah my problem its working great now, by the way could I _contribute_ to this project as I stated above, please?

**Comment by mmaaz60** [comment]
Yes, the pull requests are welcome. 

However, the code is not open source yet. We are working to make it open source soon. Stay tuned!

**Comment by apneduniya** [comment]
Really great to hear that after the code would be open sourced then please assign this to me (you can do now too) 😃 .
