### ISSUE TITLE
Training GPU Device minimum Require Specs.

### ISSUE THREAD

**Issue by BigJoon** [mbzuai-oryx/Video-ChatGPT#32]
Thanks for your wonderful work.

I saw you used 8 A100 40GB GPUs.

Is it possible to learn with 4 x RTX A6000 GPUs?

**Comment by mmaaz60** [comment]
Hi @BigJoon,

Thank you for your interest in our work.

Training on `4 x RTX A6000 GPUs` is possible. Please set the `--gradient_accumulation_steps 2` to match the overall batch size used in our experiments.

Good Luck!

**Comment by BigJoon** [comment]
Thanks for your reply, @mmaaz60 

I think this work is very interesting. I'll try to make a contribution someday.

**Comment by Xinxinatg** [comment]
> Hi @BigJoon,
> 
> Thank you for your interest in our work.
> 
> Training on `4 x RTX A6000 GPUs` is possible. Please set the `--gradient_accumulation_steps 2` to match the overall batch size used in our experiments.
> 
> Good Luck!

would 2 A30 be able to support the training?

**Comment by hkuit** [comment]
Thanks for your wonderful work.

Is it possible to learn with 1 A100 80 GPUs? Thanks
