### ISSUE TITLE
the version of transformers

### ISSUE THREAD

**Issue by zhl98** [mbzuai-oryx/Video-ChatGPT#34]
I can not get the version of transformers transformers@git+https://github.com/huggingface/transformers.git@cae78c46. 
Can you give me some help?

**Comment by hanoonaR** [comment]
Hi @zhl98,

The command to install transformers is `pip install transformers@git+https://github.com/huggingface/transformers.git@cae78c46`

A sample expected output is:
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/58504617/02f65251-6f1a-42ad-8032-305edf82e852)
