### ISSUE TITLE
Demo is dead :cry: 

### ISSUE THREAD

**Issue by karrymao** [mbzuai-oryx/Video-ChatGPT#35]
The [demo page](https://www.ival-mbzuai.com/video-chatgpt) is dead, it gives
```
ERR_NGROK_3200
Tunnel video-chatgpt.ngrok.app not found
```
Hope it will be fixed soon.

**Comment by hanoonaR** [comment]
Hi @karrymao ,

Thank you for notifying. We have fixed the issue, kindly check again. Thank you.
