### ISSUE TITLE
Can I apply your weights to vicuna 13b or 33b?

### ISSUE THREAD

**Issue by msarkeshi** [mbzuai-oryx/Video-ChatGPT#36]

**Comment by hanoonaR** [comment]
Hi @msarkeshi,

The Vicuna 13B and 33B models have different hidden dimensions compared to the Vicuna 7B. As a result, our linear layer projections, which have been tuned specifically for the 7B model, will not be directly compatible with these models. 

Thank you.

**Comment by mmaaz60** [comment]
Hi @mehdisarkeshi,

One of the quickest solutions could be to explicitly instruct the model to be brief. However, a better solution could be to use a bigger model and cleaner data.
