### ISSUE TITLE
pydantic version problem

### ISSUE THREAD

**Issue by Creator404** [mbzuai-oryx/Video-ChatGPT#40]
I have the same problem like https://github.com/adw0rd/instagrapi/issues/1435

Just looks like:
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
profile_pic_url
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
profile_pic_url_hd
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
is_private
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing

I follow the instructions that revoke the pydantic version from 2.0.x to 1.10.9, then the project can work properly.

plz insert into requirements.txt:
pydantic==1.10.9

**Comment by mmaaz60** [comment]
Hi @Creator404,

Thank you for pointing it out. We have updated the `requirements.txt` file. Thanks
