### ISSUE TITLE
openai/clip-vit-large-patch14 were not used when initializing CLIPVisionModel

### ISSUE THREAD

**Issue by minuenergy** [mbzuai-oryx/Video-ChatGPT#43]
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/72018553/59843bf8-ff7c-4256-ba6d-1743b4e5890d)

I running this command 
python video_chatgpt/demo/video_demo.py \
--model-name Video-ChatGPT_Models/LLaVA-Lightning-7B-v1-1 \
--projection_path Video-ChatGPT_Models/video_chatgpt-7B.bin

It seems to work well with this, but I'm not sure if this is really okay, any advice would be appreciated.

**Comment by jhj7905** [comment]
@minuenergy 
No problem, some weights in picture belong to encoder.
Don't worry

**Comment by mmaaz60** [comment]
Hi

As pointed by @jhj7905, these warnings are expected. Thanks

**Comment by chakrabortyrajatsubhra** [comment]
Hi, a followup to this question can we use vit base version instead of large while inferencing and from exactly where do we get the above warning as this not in the code base as far as I saw.
