### ISSUE TITLE
Llama 2 7B

### ISSUE THREAD

**Issue by roninio** [mbzuai-oryx/Video-ChatGPT#46]
Hi great project

I am trying to run it with Llama 2. I have followed the steps. I am getting Hallucinations. 

Can it be done with Llama 2 7B ?

**Comment by mmaaz60** [comment]
Hi @roninio,

Thank you for your interest in our work. Currently, we don't have a LLaMA-2 based pretrained model and in order to use Video-ChatGPT with LLaMA, you have train the model on our Video Instruction Dataset.

However, we may release LLaMA-2 based models soon. Stay Tuned, Thank you.
