### ISSUE TITLE
Loss curve during training

### ISSUE THREAD

**Issue by FanScy** [mbzuai-oryx/Video-ChatGPT#49]
Hi, thank you for sharing the great work!
Could you share the loss curve during training?

**Comment by mmaaz60** [comment]
Hi @FanScy,

Thank You for you interest in our work. The training logs are attached.
[trainer_state.json.zip](https://github.com/mbzuai-oryx/Video-ChatGPT/files/12494869/trainer_state.json.zip)

**Comment by FanScy** [comment]
Thanks! 
It converges so quickly
