### ISSUE TITLE
can I train in one A100 80G GPU?

### ISSUE THREAD

**Issue by hkuit** [mbzuai-oryx/Video-ChatGPT#51]
Hello, thanks for the great work.

Can I train the model using only one A100 80G GPU? Or how can we modify the code so that it can be trained on one gpu? Thank you so much.

**Comment by mmaaz60** [comment]
Hi @hkuit,

Yes, you can train on a single A100-80G GPU. Please make sure to keep the overall batch size to 32. This can be achieved by  using the following setting,
```
--per_device_train_batch_size 8 \
--gradient_accumulation_steps 4 \
```
Please let me know if it works. Thanks

**Comment by hkuit** [comment]
Thank you for the reply @mmaaz60 , let me try it and update to you later.

**Comment by hkuit** [comment]
Thanks @mmaaz60 , it works. But there is another error appear. When I save the checkpoint on step 3000, after that the error "RuntimeError: Parent directory /media/user/data1/Video-ChatGPT/Video-ChatGPT_7B-1.1_Checkpoints/checkpoint-3000 does not exist." happened.  " Looking forward to your suggestion, thank you again.

**Comment by hkuit** [comment]
Thanks, it works.
