### ISSUE TITLE
What is the size of the model compared in the experiment?

### ISSUE THREAD

**Issue by jpthu17** [mbzuai-oryx/Video-ChatGPT#52]
Thank you for sharing the good work!

I'm very interested in your work, but I have some questions about the details of the experiment. In the following table, is the Video Chat version 13b or 7b? Also, is Video LLama version 13b or 7b? Looking forward to your reply.

![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/53246557/0c2f8b0a-9b84-4f75-b29f-19427d6ab609)

**Comment by mmaaz60** [comment]
Hi @jpthu17,

Thank you for your interest in our work. For conducting a fair comparison, we use 7B version of all the methods in our benchmark.

**Comment by jpthu17** [comment]
Thank you for your prompt response. I appreciate your help.
