### ISSUE TITLE
model inference

### ISSUE THREAD

**Issue by Xiuyuan-Chen** [mbzuai-oryx/Video-ChatGPT#53]
Could you please post a code reasoning script that doesn't use gradio, thank you very much!

**Comment by ee2110** [comment]
Hi, thank you for the great work! I am also keen to know how can we make inferences without using the interface. For example, I have a list of videos, and I would like to make this model to iterate over the video list and generate output for each video.

**Comment by mmaaz60** [comment]
Hi @khhuiyh, @ee2110,

Please have a look at #59, thanks
