### ISSUE TITLE
online demo doesn't work now

### ISSUE THREAD

**Issue by nigelnew** [mbzuai-oryx/Video-ChatGPT#56]
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/43841092/54499aea-be87-46c0-9e9a-bc14255f9f53)

ERR_NGROK_3200
Tunnel video-chatgpt.ngrok.app not found

[Get help with this error](https://ngrok.com/docs/errors/err_ngrok_3200)
If you're the developer of this page
Check out the docs to get [help with this error](https://ngrok.com/docs/errors/err_ngrok_3200).

If you're a visitor of this page
Wait a few minutes and refresh the page. If that still doesn't work, please contact the developer of this page for more information.

**Comment by mmaaz60** [comment]
Hi @nigelnew,

Video-ChatGPT online demo is terminated, and you are recommended to run the offline demo instead following [offline_demo.md](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/docs/offline_demo.md).

Apologies for the inconvenience caused. Thank You.
