### ISSUE TITLE
Can't download weights using transformers api

### ISSUE THREAD

**Issue by AnaRhisT94** [mbzuai-oryx/Video-ChatGPT#6]
Hi,
When using the code below to download the weights I'm getting an error key regarding LLava.
```
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("mmaaz60/LLaVA-7B-Lightening-v1-1")
```

**Comment by mmaaz60** [comment]
Hi @AnaRhisT94,

Thank You for your interest in our work. Please share some more details about the error? Also, please make sure that you are using the recommended version of transformers as in [requirements.txt](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/requirements.txt).

```
pip install transformers@git+https://github.com/huggingface/transformers.git@cae78c46
```

Alternatively, you can also download the same model from [here](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EUv0wVEM6n9JuONbCEvdAvEBd68U_r3bQY4SD-8wgxLNTA?e=lb21aa).

Please let me know if it solves the issue. Thank You
