### ISSUE TITLE
CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by tkarthikeyan132** [mbzuai-oryx/Video-ChatGPT#62]
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/49520037/afd8e88e-9cd5-489c-97e9-eb2f44085584)

while I was running the training code, i faced this issue
NOTE: I have 2 A100 gpus and 8 cpus

**Comment by mmaaz60** [comment]
Hi @tkarthikeyan132,

Thank you for your interest in our work. Please share the script you are running and the command you are using for reproducing the issue. Thanks

**Comment by tkarthikeyan132** [comment]
Hi @mmaaz60,
I haven't changed the script and I run the torchrun command,
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/49520037/0944540a-8ed2-40f0-b763-8ea0e1cf65e6)
