### ISSUE TITLE
Offline models and dataset download 

### ISSUE THREAD

**Issue by KerolosAtef** [mbzuai-oryx/Video-ChatGPT#63]
could you provide a direct link to download the offline folder that contains models and data using wget

**Comment by mmaaz60** [comment]
Hi @KerolosAtef,

Thank you for your interest in our work. Unfortunately, currently 'wget' links are not available. However, our model is available on HuggingFace and data annotations are available on HugginFace and videos are available as OneDrive link.

**Base LLaVA Model:** [this link](https://huggingface.co/mmaaz60/LLaVA-7B-Lightening-v1-1)
**Video-ChatGPT Projection Weights:** [this link](https://huggingface.co/MBZUAI/Video-ChatGPT-7B)

**Dataset Videos:** [this link](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EhRI02jGteRIqeDqM2brzOEBu2yO7xaQ4KXdEGNrVYKq6Q?e=XTQcgn)
**Dataset Annotations:** [this link](https://huggingface.co/datasets/MBZUAI/VideoInstruct-100K)

**Comment by KerolosAtef** [comment]
Hi @mmaaz60 
thank you for these links, if there is a link for the dataset videos in google drive it will be good because I can't download the data using terminal in this way, however in google drive, I will use gdown library.
I'm using terminal because I want to download this dataset to a server which hasn't a GUI.

**Comment by mmaaz60** [comment]
Hi @KerolosAtef,

You may use [this gdrive link](https://drive.google.com/file/d/1Mb45IO7ArEjgdOg140mvSMOMNvIZOXml/view?usp=drivesdk). Thanks

**Comment by KerolosAtef** [comment]
Great, thank you very much, only the last thing, could you make it access to everyone with the link because gdown only works for the public links.

**Comment by mmaaz60** [comment]
> Great, thank you very much, only the last thing, could you make it access to everyone with the link because gdown only works for the public links.

Can you try [this link](https://drive.google.com/file/d/1Mb45IO7ArEjgdOg140mvSMOMNvIZOXml/view?usp=sharing)?
