### ISSUE TITLE
Where to download the video in MSRVTT-QA & How to evaluate TGIF-QA

### ISSUE THREAD

**Issue by wcy1122** [mbzuai-oryx/Video-ChatGPT#65]
Hello, thanks for providing this outstanding work.
May I know where to download video in MSRVTT-QA?
It looks like the official website [https://ms-multimedia-challenge.com/2016/dataset] is no longer maintained.
Thanks

**Comment by wcy1122** [comment]
Thanks for your reply.
By the way, did you use the question in test_qa for MSVD-QA and MSRVTT-QA evaluation?
However, did you use all questions in Test_xxx_question.csv for TGIF-QA evaluation?
Thanks

**Comment by wcy1122** [comment]
One more question, how to get ground-truth answer for questions in TGIF-QA?
I found 5 answers in Test_xxx_question.csv files for each question, and not sure how to generate the answer for GPT 3.5 evaluation.
Thanks.

**Comment by KerolosAtef** [comment]
I have the same questions regarding TGIF-QA , I hope anyone can reply.
@hanoonaR

**Comment by hanoonaR** [comment]
Hi @wcy1122 ,

Thank you for your interest in our work and apologies for the delayed response. We use the validation set for [MSVD](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/Eeoc0dCbhuFGvpJN0csStFcBSsajcV6hsYU6Yzw9No-Vyg?e=euSNcg) and [MSRVTT](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EXCVnB-P1L9HggLpR4quVFIBlLwcUSMwqg2VyvanDHyshA?e=Svx18a) and the test set for [TGIF](https://mbzuaiac-my.sharepoint.com/:x:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EUtsDPPdxmlBnzE5ep82wVwBNwzdQknS3VgzNNOOIffbUw?e=POdBoG). A copy of the annotation files have been attached in the links.

Please let us know if you have any further questions.

Thank you.

**Comment by SCZwangxiao** [comment]
> Hi @wcy1122 ,
> 
> Thank you for your interest in our work and apologies for the delayed response. We use the validation set for [MSVD](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/Eeoc0dCbhuFGvpJN0csStFcBSsajcV6hsYU6Yzw9No-Vyg?e=euSNcg) and [MSRVTT](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EXCVnB-P1L9HggLpR4quVFIBlLwcUSMwqg2VyvanDHyshA?e=Svx18a) and the test set for [TGIF](https://mbzuaiac-my.sharepoint.com/:x:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EUtsDPPdxmlBnzE5ep82wVwBNwzdQknS3VgzNNOOIffbUw?e=POdBoG). A copy of the annotation files have been attached in the links.
> 
> Please let us know if you have any further questions.
> 
> Thank you.

Thank you for the response. And I think better highlight that you r using TFIG-QA Frame
