### ISSUE TITLE
Where to download the video in TGIF-QA

### ISSUE THREAD

**Issue by LinB203** [mbzuai-oryx/Video-ChatGPT#66]
Great work!
Could you provide annotations and video for evaluating on TGIF? or where to obtain these? appreciating for your instruction!

**Comment by mmaaz60** [comment]
Hi @LinB203,

You can find it at [this link](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EeoWE0IMcdlNjXvP2KvezFoBhijHw3b32Kyq1Fa2K8ASXA?e=ZLchCg).

**Comment by LinB203** [comment]
THANKS, and I also need the annotations such test_q.json and test_a.json for TGIF-QA. Thanks again!

> Hi @LinB203,
> 
> You can find it at [this link](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EeoWE0IMcdlNjXvP2KvezFoBhijHw3b32Kyq1Fa2K8ASXA?e=ZLchCg).

**Comment by wcy1122** [comment]
> Hi @LinB203,
> 
> You can find it at [this link](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EeoWE0IMcdlNjXvP2KvezFoBhijHw3b32Kyq1Fa2K8ASXA?e=ZLchCg).

Hello, thanks for providing this.
However, I found lots of mp4 files cannot be opened in this zip file.
Do you use these videos for zero-shot evaluation?
It would be best if you could provide the test_q.json and test_a.json for TGIF-QA.

Thanks.

**Comment by mmaaz60** [comment]
Please refer to Issue #96
