### ISSUE TITLE
Where can we download the video for VideoInstruct-100K?

### ISSUE THREAD

**Issue by oximi123** [mbzuai-oryx/Video-ChatGPT#67]
Can you provide a link for the videos mentioned in the  VideoInstruct-100K dataset?

**Comment by mmaaz60** [comment]
Hi @oximi123,

The videos can be found at [this link](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EhRI02jGteRIqeDqM2brzOEBvBA5WiEhxso2QU7Iqysnew?e=YdwxUf). Note that the videos are distributed into multiple tar files (each of around 5 GB) for the ease of download.

Thanks
