### ISSUE TITLE
MSVD-QA and MSRVTT-QA evaluation

### ISSUE THREAD

**Issue by KerolosAtef** [mbzuai-oryx/Video-ChatGPT#68]
for the results in the few shot table which file did you use test_qa or val_qa for MSVD-QA and MSRVTT-QA evaluation

**Comment by hanoonaR** [comment]
Hi @KerolosAtef ,

Thank you for your interest in our work and apologies for the late response. We use the validation set for [MSVD](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/Eeoc0dCbhuFGvpJN0csStFcBSsajcV6hsYU6Yzw9No-Vyg?e=euSNcg) and [MSRVTT](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EXCVnB-P1L9HggLpR4quVFIBlLwcUSMwqg2VyvanDHyshA?e=Svx18a) and the test set for [TGIF](https://mbzuaiac-my.sharepoint.com/:x:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EUtsDPPdxmlBnzE5ep82wVwBNwzdQknS3VgzNNOOIffbUw?e=POdBoG). A copy of the annotation files have been attached in the links.

Thank you
