### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by AnaRhisT94** [mbzuai-oryx/Video-ChatGPT#7]
Hi,

Edit: I see that I need python 3.10 now, will update

When using: `python video_chatgpt/demo/video_demo.py --model-name /notebooks/LLaVA-7B-Lightening-v1-1 --projection_path /notebooks/Video-ChatGPT`

I'm getting the following error:

![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/33227900/111029d1-b5de-4f7c-a2a2-5acd7edf8ec1)

**Comment by hanoonaR** [comment]
Hi @AnaRhisT94 ,

Thank you for your interest in our work. Kindly make sure that you use the recommended environment: python 3.10 and [python packages](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/requirements.txt). 

Thank you.
