### ISSUE TITLE
ActivityNet few shot videos can't be downloaded 

### ISSUE THREAD

**Issue by KerolosAtef** [mbzuai-oryx/Video-ChatGPT#73]
Could you please provide a google drive link for ActivityNet test videos for few shot evaluation instead of this 
https://mbzuaiacmy.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/ESa302OCJMNHsMk7wuBbQc8BZH5CqlcdCWiSpXynQZDfAQ?e=CrOPbm

The google drive link will be easy to download using the gdown library and use this files directly on the servers, because I can't download these videos using wget and curl commands.
if you have a direct link for them which working with wget or curl will be good also.

**Comment by mmaaz60** [comment]
Hi @KerolosAtef

The following is what you are looking for? Thanks

https://drive.google.com/file/d/1RzDNZ1qF3FHG5wuL6bPHgLtU79Qo-pRV/view?usp=drive_link

**Comment by KerolosAtef** [comment]
yes , could you change the access to public (anyone with the link)

**Comment by mmaaz60** [comment]
Please try now, thanks

**Comment by wangyu-ustc** [comment]
I'm still getting this error:

Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1Mb45IO7ArEjgdOg140mvSMOMNvIZOXml

**Comment by mmaaz60** [comment]
Hi @wangyu-ustc,

Were you able to download? Thanks

**Comment by shiyuanh** [comment]
I am having the same access error when I tried to use `gdown` for downloading from google drive. Also tried downloading from browser but kept failing due to network error. Could you split the .zip file into multiple smaller parts for easier downloading?

**Comment by mmaaz60** [comment]
Hi @shiyuanh,

You may use the following huggingface dataset to download all videos. It contains small `tar` files.

https://huggingface.co/datasets/mmaaz60/ActivityNet-QA-Test-Videos
