### ISSUE TITLE
Llava Weights not available for running demo offline

### ISSUE THREAD

**Issue by chakrabortyrajatsubhra** [mbzuai-oryx/Video-ChatGPT#80]
I tried to do this way -- "download the ready LLaVA-Lightening-7B weights from [mmaaz60/LLaVA-Lightening-7B-v1-1](https://huggingface.co/mmaaz60/LLaVA-7B-Lightening-v1-1)" but there were no weights there how to get the converted weights?? I tried the first way also-- "Get the original LLaMA weights in the huggingface format by following the instructions [here](https://huggingface.co/docs/transformers/main/model_doc/llama)." but never received any weights. Can you provide with the LLaVa weights?

**Comment by mmaaz60** [comment]
Hi @chakrabortyrajatsubhra,

Thank you for your interest in our work. You can use the following git lfs commands to get the LLaVA weights,

```
git lfs install
git clone https://huggingface.co/mmaaz60/LLaVA-7B-Lightening-v1-1
```

Thanks.

**Comment by chakrabortyrajatsubhra** [comment]
Thank you so much, I have one additional question to ask if you can answer.
While doing the offline inference if I want to use CLIP -VIT -Base patch 32
as the feature extractor instead of vit large patch 14 is that possible?
And where in the code should i make changes?
Looking forward for your reply.
Thanks
Rajatsubhra Chakraborty
