### ISSUE TITLE
Clarification Needed on the Role of **QA_GT_caption_based_noisy** in the Dataset

### ISSUE THREAD

**Issue by FlorientHuang** [mbzuai-oryx/Video-ChatGPT#82]
Hello,

I am currently working with a dataset and have come across the QA_GT_caption_based_noisy tag. However, its role and purpose within the dataset are unclear to me. There are instances where this tag appears in the inference output. Could you please provide some insight into what this tag signifies? Is it something that we can safely remove or ignore during our processes?

Thank you for your assistance and time in addressing this query.

**Comment by mmaaz60** [comment]
Hi @FlorientHuang,

Thank you for your interest in our work. This might be related to the noise due to automatic annotations. It can be removed/filtered from the annotations. Thanks
