### ISSUE TITLE
About zero-shot test on TGIF-QA

### ISSUE THREAD

**Issue by msra-jqxu** [mbzuai-oryx/Video-ChatGPT#84]
Hi @mmaaz60 ,
I noticed that there are four tasks on the testset of the TGIF-QA dataset: Repetition count, Repeating action, State transition and Frame QA. Are the results of TGIF-QA(51.40/3.0) in your experiments obtained by testing on these four tasks (a total of 25,751 QA pairs)? Or was it just tested on Frame QA? Thanks！
The below table is the statistics of TGIF-QA.
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/53702716/843b6f16-6e00-4f77-91cd-1903ce87ee8e)

**Comment by mmaaz60** [comment]
Hi @msra-jqxu,

Thank you for your interest in our work. We used TGIF Frame QA only in our experiments for all the compared methods. Thank you.
