### ISSUE TITLE
Train errors: some videos in train_video_ids.txt do not appear in activity_clip-14L_spatio_temporal_356

### ISSUE THREAD

**Issue by DemoGit4LIANG** [mbzuai-oryx/Video-ChatGPT#87]
some videos in train_video_ids.txt do not appear in activity_clip-14L_spatio_temporal_356

**Comment by mmaaz60** [comment]
Hi @DemoGit4LIANG,

Thank you for your interest in our work. The issue #16 would be helpful for you to resolve the error. Please let me know if you still face any issues. Thank You.

**Comment by DemoGit4LIANG** [comment]
> Hi @DemoGit4LIANG,
> 
> Thank you for your interest in our work. The issue #16 would be helpful for you to resolve the error. Please let me know if you still face any issues. Thank You.

I only find the link of "VideoInstruct_Dataset.json" and do not find the link of "VideoInstruct_Dataset_Train.json" you mentioned in #16 , and "VideoInstruct_Dataset.json" also cause mismatch.

**Comment by DemoGit4LIANG** [comment]
> Hi @DemoGit4LIANG,
> 
> Thank you for your interest in our work. The issue #16 would be helpful for you to resolve the error. Please let me know if you still face any issues. Thank You.

Thanks. It works.
