### ISSUE TITLE
Insufficient VRAM on a single card, how to utilize multiple cards for inference

### ISSUE THREAD

**Issue by ds-gong** [mbzuai-oryx/Video-ChatGPT#93]
Hi, I have 2 * 2080TI, each GPU card has 12GB of memory. 
How can I use the two GPU cards for inference?
![Uploading 111.png…]()

**Comment by mmaaz60** [comment]
Hi @ds-gong,

Thanks for your interest in our work. Unfortunately, currently we only support single GPU inference.
