### ISSUE TITLE
Why TGIF videos missed and can't be processed

### ISSUE THREAD

**Issue by FlorientHuang** [mbzuai-oryx/Video-ChatGPT#96]
Hello,

I've been exploring the TGIF Videos dataset as mentioned in this link: [TGIF_DATASET][url]
 However, I've encountered a couple of issues that I hope can be addressed:

Missing Videos: Upon examining the Test_frameqa_question.csv file and other annotation files, I noticed that several videos referenced are not included in the provided ZIP file.

Processing Errors: Approximately half of the videos in the dataset cannot be processed. For example, attempts to process the file at /mnt/nlp-ali/dataset/vllm/Video_ChatGPT_Dataset/Zero_Shot_QA_Dataset/TGIF-QA/videos_mp4/tumblr_nc6dweKA4W1tmwagjo1_250.mp4 resulted in errors stating "Invalid data found when processing input" and further detail on the inability to open and read the video file.
Failed info:
[09:54:30] /github/workspace/src/video/video_reader.cc:83: ERROR opening: /mnt/nlp-ali/dataset/vllm/Video_ChatGPT_Dataset/Zero_Shot_QA_Dataset/TGIF-QA/videos_mp4/tumblr_nhqa0w4T6e1u7c3syo1_250.mp4, Invalid data found when processing input
Can't process /mnt/nlp-ali/dataset/vllm/Video_ChatGPT_Dataset/Zero_Shot_QA_Dataset/TGIF-QA/videos_mp4/tumblr_nhqa0w4T6e1u7c3syo1_250.mp4: Error reading /mnt/nlp-ali/dataset/vllm/Video_ChatGPT_Dataset/Zero_Shot_QA_Dataset/TGIF-QA/videos_mp4/tumblr_nhqa0w4T6e1u7c3syo1_250.mp4...

Could you please look into these issues? It would greatly aid in utilizing the dataset for research and development purposes.

Thank you for your assistance and for providing such a valuable resource to the community.

[url]: https://mbzuaiac-my.sharepoint.com/personal/hanoona_bangalath_mbzuai_ac_ae/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FQuantitative%5FEvaluation%2Fvideo%2Dchatgpt%5Fzeroshot%5Fevaluation%5Ftgif%2Ezip&parent=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FQuantitative%5FEvaluation&ga=1

**Comment by mmaaz60** [comment]
Hi @FlorientHuang,

Thank you for your interest in our work. It looks like the link I shared before does contain many corrupted videos. Apologies for the inconvenience.

I have downloaded the GIFs again from the original [source](https://github.com/YunseokJANG/tgif-qa/blob/master/dataset/README.md) and uploaded at [google drive](https://drive.google.com/file/d/1FfVnZgxYwyEf1u_3_osa0kw8Pb9nlzn5/view?usp=sharing) for your reference.

Note that the the link contain original GIFs and you may have to convert them into mp4 format before running the inference.

I hope it will help. Thanks.

**Comment by FlorientHuang** [comment]
> Hi @FlorientHuang,
> 
> Thank you for your interest in our work. It looks like the link I shared before does contain many corrupted videos. Apologies for the inconvenience.
> 
> I have downloaded the GIFs again from the original [source](https://github.com/YunseokJANG/tgif-qa/blob/master/dataset/README.md) and uploaded at [google drive](https://drive.google.com/file/d/1FfVnZgxYwyEf1u_3_osa0kw8Pb9nlzn5/view?usp=sharing) for your reference.
> 
> Note that the the link contain original GIFs and you may have to convert them into mp4 format before running the inference.
> 
> I hope it will help. Thanks.

Thanks a lot

**Comment by mmaaz60** [comment]
Thanks @FlorientHuang,

Good Luck and feel free to ask any further questions that you may have. Thanks
