### ISSUE TITLE
Download videos

### ISSUE THREAD

**Issue by ZenMoore** [mbzuai-oryx/Video-ChatGPT#98]
Hello, 

I am wondering how can I get access to the videos?
There is no raw videos in the onedrive link: https://mbzuaiac-my.sharepoint.com/personal/hanoona_bangalath_mbzuai_ac_ae/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT.

So where are the videos? Or how can I download the raw videos?

Thanks.

**Comment by mmaaz60** [comment]
Hi @ZenMoore,

I hope you are doing well. All the videos are available at [this onedrive link](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EnLRDehrr8lGqHpC5w1zZ9QBnsiVffYy5vCv8Hl14deRcg?e=Ul5DUE).

Further, the following links might be useful as well.

1. [gdrive link for training videos](https://drive.google.com/file/d/1Mb45IO7ArEjgdOg140mvSMOMNvIZOXml/view?usp=sharing)
2. [ActivityNet-QA-Test-Videos](https://huggingface.co/datasets/mmaaz60/ActivityNet-QA-Test-Videos)

**Comment by Geometryyy** [comment]
> Hi @ZenMoore,
> 
> I hope you are doing well. All the videos are available at [this onedrive link](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EnLRDehrr8lGqHpC5w1zZ9QBnsiVffYy5vCv8Hl14deRcg?e=Ul5DUE).
> 
> Further, the following links might be useful as well.
> 
> 1. [gdrive link for training videos](https://drive.google.com/file/d/1Mb45IO7ArEjgdOg140mvSMOMNvIZOXml/view?usp=sharing)
> 2. [ActivityNet-QA-Test-Videos](https://huggingface.co/datasets/mmaaz60/ActivityNet-QA-Test-Videos)

hello, i really appriciate your awesome work. i would like to know what is the differences among the 4 file/folders in your onedrive link(https://mbzuaiac-my.sharepoint.com/:f:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EnLRDehrr8lGqHpC5w1zZ9QBnsiVffYy5vCv8Hl14deRcg?e=Ul5DUE).
