### ISSUE TITLE
How many frames are sampled per video for the training and testing process?

### ISSUE THREAD

**Issue by Nastu-Ho** [mbzuai-oryx/Video-ChatGPT#99]

**Comment by mmaaz60** [comment]
Hi @Nastu-Ho,

Thank you for your interest in our work. We sample 100 frames uniformly during both training and testing. Thank you

**Comment by onlyonewater** [comment]
@mmaaz60 , hi, can I sample more than 100 frames to infer on my own dataset?

**Comment by onlyonewater** [comment]
from https://github.com/mbzuai-oryx/Video-ChatGPT/issues/14, I know how to change the code, but how to change the code to extract the 1 frame or 2 frames per second? I think this implementation makes sense for long videos.

**Comment by onlyonewater** [comment]
ok, I got it, thanks @mmaaz60
